import { describe, expect, it } from 'vitest'
import { PERMISSIONS, ROLE_PERMISSIONS, ROLES } from './permissions.js'

describe('role permissions', () => {
  it('freezes the formal account role set', () => {
    expect(Object.values(ROLES)).toEqual([
      'member',
      'admin',
      'organization_admin',
      'organization_member',
      'super_admin',
      'owner',
    ])
  })

  it('freezes the role permission matrix', () => {
    expect(ROLE_PERMISSIONS).toEqual({
      member: [
        PERMISSIONS.PROJECT_READ,
        PERMISSIONS.PROJECT_WRITE,
        PERMISSIONS.GENERATION_TASK_CREATE,
        PERMISSIONS.GENERATION_TASK_READ,
        PERMISSIONS.ASSET_READ,
        PERMISSIONS.ASSET_WRITE,
        PERMISSIONS.ASSET_LIBRARY_READ,
        PERMISSIONS.ASSET_LIBRARY_WRITE,
        PERMISSIONS.BILLING_READ_SELF,
        PERMISSIONS.USAGE_READ_SELF,
      ],
      admin: [
        PERMISSIONS.PROJECT_READ,
        PERMISSIONS.PROJECT_WRITE,
        PERMISSIONS.GENERATION_TASK_CREATE,
        PERMISSIONS.GENERATION_TASK_READ,
        PERMISSIONS.ASSET_READ,
        PERMISSIONS.ASSET_WRITE,
        PERMISSIONS.ASSET_LIBRARY_READ,
        PERMISSIONS.ASSET_LIBRARY_WRITE,
        PERMISSIONS.BILLING_READ_SELF,
        PERMISSIONS.USAGE_READ_SELF,
        PERMISSIONS.BILLING_READ_ALL,
        PERMISSIONS.BILLING_MANAGE,
        PERMISSIONS.USAGE_READ_SCOPED,
        PERMISSIONS.USER_READ,
        PERMISSIONS.USER_MANAGE,
        PERMISSIONS.ADMIN_DASHBOARD_READ,
      ],
      organization_admin: [
        PERMISSIONS.PROJECT_READ,
        PERMISSIONS.PROJECT_WRITE,
        PERMISSIONS.GENERATION_TASK_CREATE,
        PERMISSIONS.GENERATION_TASK_READ,
        PERMISSIONS.ASSET_READ,
        PERMISSIONS.ASSET_WRITE,
        PERMISSIONS.ASSET_LIBRARY_READ,
        PERMISSIONS.ASSET_LIBRARY_WRITE,
        PERMISSIONS.BILLING_READ_ALL,
        PERMISSIONS.BILLING_MANAGE,
        PERMISSIONS.USAGE_READ_SELF,
        PERMISSIONS.USAGE_READ_SCOPED,
        PERMISSIONS.USER_READ,
        PERMISSIONS.USER_MANAGE,
        PERMISSIONS.ADMIN_DASHBOARD_READ,
      ],
      organization_member: [
        PERMISSIONS.PROJECT_READ,
        PERMISSIONS.PROJECT_WRITE,
        PERMISSIONS.GENERATION_TASK_CREATE,
        PERMISSIONS.GENERATION_TASK_READ,
        PERMISSIONS.ASSET_READ,
        PERMISSIONS.ASSET_WRITE,
        PERMISSIONS.ASSET_LIBRARY_READ,
        PERMISSIONS.ASSET_LIBRARY_WRITE,
        PERMISSIONS.BILLING_READ_SELF,
        PERMISSIONS.USAGE_READ_SELF,
      ],
      super_admin: [
        PERMISSIONS.PROJECT_READ,
        PERMISSIONS.PROJECT_WRITE,
        PERMISSIONS.GENERATION_TASK_CREATE,
        PERMISSIONS.GENERATION_TASK_READ,
        PERMISSIONS.ASSET_READ,
        PERMISSIONS.ASSET_WRITE,
        PERMISSIONS.ASSET_LIBRARY_READ,
        PERMISSIONS.ASSET_LIBRARY_WRITE,
        PERMISSIONS.BILLING_READ_SELF,
        PERMISSIONS.BILLING_READ_ALL,
        PERMISSIONS.BILLING_MANAGE,
        PERMISSIONS.USAGE_READ_SELF,
        PERMISSIONS.USAGE_READ_SCOPED,
        PERMISSIONS.USAGE_READ_ALL,
        PERMISSIONS.USER_READ,
        PERMISSIONS.USER_MANAGE,
        PERMISSIONS.ADMIN_DASHBOARD_READ,
      ],
      owner: [
        PERMISSIONS.PROJECT_READ,
        PERMISSIONS.PROJECT_WRITE,
        PERMISSIONS.GENERATION_TASK_CREATE,
        PERMISSIONS.GENERATION_TASK_READ,
        PERMISSIONS.ASSET_READ,
        PERMISSIONS.ASSET_WRITE,
        PERMISSIONS.ASSET_LIBRARY_READ,
        PERMISSIONS.ASSET_LIBRARY_WRITE,
        PERMISSIONS.BILLING_READ_SELF,
        PERMISSIONS.BILLING_READ_ALL,
        PERMISSIONS.BILLING_MANAGE,
        PERMISSIONS.USAGE_READ_SELF,
        PERMISSIONS.USAGE_READ_SCOPED,
        PERMISSIONS.USAGE_READ_ALL,
        PERMISSIONS.USER_READ,
        PERMISSIONS.USER_MANAGE,
        PERMISSIONS.ADMIN_DASHBOARD_READ,
        PERMISSIONS.SYSTEM_CONFIG_MANAGE,
      ],
    })
  })

  it('grants owners every declared permission', () => {
    expect(new Set(ROLE_PERMISSIONS.owner)).toEqual(new Set(Object.values(PERMISSIONS)))
  })

  it('gives super admins the operational permissions without system config access', () => {
    expect(ROLE_PERMISSIONS.super_admin).toContain(PERMISSIONS.ADMIN_DASHBOARD_READ)
    expect(ROLE_PERMISSIONS.super_admin).toContain(PERMISSIONS.USER_MANAGE)
    expect(ROLE_PERMISSIONS.super_admin).toContain(PERMISSIONS.BILLING_MANAGE)
    expect(ROLE_PERMISSIONS.super_admin).toContain(PERMISSIONS.USAGE_READ_ALL)
    expect(ROLE_PERMISSIONS.super_admin).not.toContain(PERMISSIONS.SYSTEM_CONFIG_MANAGE)
  })

  it('keeps creator out of the formal account role contract', () => {
    expect(Object.values(ROLES)).not.toContain('creator')
  })

  it('does not expose admin capabilities to members', () => {
    expect(ROLE_PERMISSIONS.member).not.toContain(PERMISSIONS.ADMIN_DASHBOARD_READ)
    expect(ROLE_PERMISSIONS.member).not.toContain(PERMISSIONS.BILLING_MANAGE)
    expect(ROLE_PERMISSIONS.member).not.toContain(PERMISSIONS.USER_MANAGE)
    expect(ROLE_PERMISSIONS.member).toContain(PERMISSIONS.USAGE_READ_SELF)
    expect(ROLE_PERMISSIONS.member).not.toContain(PERMISSIONS.USAGE_READ_SCOPED)
    expect(ROLE_PERMISSIONS.member).not.toContain(PERMISSIONS.USAGE_READ_ALL)
    expect(ROLE_PERMISSIONS.organization_member).toEqual(ROLE_PERMISSIONS.member)
  })

  it('allows admins to inspect operations without changing system configuration', () => {
    expect(ROLE_PERMISSIONS.admin).toContain(PERMISSIONS.ADMIN_DASHBOARD_READ)
    expect(ROLE_PERMISSIONS.admin).toContain(PERMISSIONS.PROJECT_WRITE)
    expect(ROLE_PERMISSIONS.admin).toContain(PERMISSIONS.GENERATION_TASK_CREATE)
    expect(ROLE_PERMISSIONS.admin).toContain(PERMISSIONS.BILLING_MANAGE)
    expect(ROLE_PERMISSIONS.admin).toContain(PERMISSIONS.USAGE_READ_SCOPED)
    expect(ROLE_PERMISSIONS.admin).not.toContain(PERMISSIONS.USAGE_READ_ALL)
    expect(ROLE_PERMISSIONS.admin).not.toContain(PERMISSIONS.SYSTEM_CONFIG_MANAGE)
    expect(ROLE_PERMISSIONS.organization_admin).toContain(PERMISSIONS.ADMIN_DASHBOARD_READ)
    expect(ROLE_PERMISSIONS.organization_admin).toContain(PERMISSIONS.USER_MANAGE)
    expect(ROLE_PERMISSIONS.organization_admin).toContain(PERMISSIONS.USAGE_READ_SCOPED)
    expect(ROLE_PERMISSIONS.organization_admin).not.toContain(PERMISSIONS.USAGE_READ_ALL)
    expect(ROLE_PERMISSIONS.organization_admin).not.toContain(PERMISSIONS.SYSTEM_CONFIG_MANAGE)
  })
})
