apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: seqora-redis-network-delay
  namespace: seqora-chaos
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - seqora-prod
    labelSelectors:
      app.kubernetes.io/name: redis
  delay:
    latency: 300ms
    jitter: 50ms
    correlation: '25'
  duration: 5m
