export const CAMERA_EMOTION_TERMS = [
  {
    id: 'pressing-push',
    name: '推近压迫镜头',
    prompt: '慢速推轨，焦点锁定人物面部，背景逐渐压缩，呼吸可闻，眼神颤动',
    scene: '心理压迫、秘密揭晓前夕',
  },
  {
    id: 'distant-pull',
    name: '后撤疏离镜头',
    prompt: '镜头缓慢后拉，人物停留原地，空间感被放大，环境吞没人像',
    scene: '失落、分手、关系疏远',
  },
  {
    id: 'dizzy-orbit',
    name: '环绕眩晕镜头',
    prompt: '围绕主体360度环拍，轻微变焦制造失衡感，背景旋转虚化',
    scene: '震惊、告白、情绪失控',
  },
  {
    id: 'breakdown-handheld',
    name: '手持崩溃镜头',
    prompt: '手持轻晃，近距离跟拍，不规则呼吸节奏式移动',
    scene: '逃亡、争吵、精神濒临崩溃',
  },
  {
    id: 'low-angle-pressure',
    name: '低角压强镜头',
    prompt: '低机位仰拍，人物轮廓强化，光影对比强烈，制造支配感',
    scene: '权力对峙、反派登场、强势宣言',
  },
  {
    id: 'isolated-overhead',
    name: '俯拍孤立镜头',
    prompt: '高机位垂直俯视，人物被环境包围，构图留白明显',
    scene: '孤独、无助、失败时刻',
  },
  {
    id: 'peeking-slide',
    name: '侧移窥视镜头',
    prompt: '镜头沿遮挡物横向移动，前景虚化遮掩主体，形成偷窥感',
    scene: '监视、秘密观察、危险逼近',
  },
  {
    id: 'fixed-stare',
    name: '定格凝视镜头',
    prompt: '固定机位长时间停留，人物微表情成为焦点，时间感被拉长',
    scene: '沉默对峙、隐忍、悲伤酝酿',
  },
  {
    id: 'rapid-push',
    name: '极速推进镜头',
    prompt: '快速推进主体，背景被迅速甩开，节奏突袭，情绪瞬间聚焦',
    scene: '惊觉、发现真相、危机来临',
  },
  {
    id: 'rack-focus-reveal',
    name: '拉焦转移镜头',
    prompt: '前后景焦点切换，注意力从一人转向另一物，信息递进揭示',
    scene: '线索出现、关系反转、暗示秘密',
  },
  {
    id: 'immersive-follow',
    name: '跟随沉浸镜头',
    prompt: '稳定器贴身跟拍，步伐同步，视角代入角色行动',
    scene: '奔赴、寻找、任务执行',
  },
  {
    id: 'vertigo-zoom',
    name: '变焦窒息镜头',
    prompt: '推拉变焦同步进行，主体比例稳定，背景空间扭曲',
    scene: '恐惧升级、危险降临、心理失衡',
  },
  {
    id: 'silhouette-resolve',
    name: '剪影决绝镜头',
    prompt: '逆光拍摄，人物面部隐藏于黑影，轮廓边缘清晰发亮',
    scene: '离别、牺牲、最终抉择',
  },
  {
    id: 'shot-reverse-pressure',
    name: '反打对峙镜头',
    prompt: '正反打快速切换，视线方向精准对应，节奏逐步加压',
    scene: '谈判、审问、激烈冲突',
  },
  {
    id: 'macro-tension',
    name: '微距失控镜头',
    prompt: '超近景拍摄眼睛、手指、嘴角等细节，捕捉细微颤动',
    scene: '紧张、欲言又止、情绪爆发前',
  },
  {
    id: 'telephoto-distance',
    name: '长焦抽离镜头',
    prompt: '远距离长焦观察，空间被压平，人物像被世界隔开',
    scene: '暗恋、旁观、无法靠近',
  },
  {
    id: 'barrier-push',
    name: '穿越障碍镜头',
    prompt: '镜头从门框、人群、玻璃等障碍间推进，增强阻隔感与目的性',
    scene: '追寻、营救、突破困境',
  },
  {
    id: 'slow-pan-omen',
    name: '慢摇预兆镜头',
    prompt: '镜头缓慢平移或摇动，逐步揭示空间信息，制造悬念',
    scene: '异样出现、危机前奏、环境铺垫',
  },
  {
    id: 'fate-crane',
    name: '升降命运镜头',
    prompt: '镜头垂直升起或下降，人物关系与处境在空间中被重组',
    scene: '命运转折、结局揭示、格局拉开',
  },
  {
    id: 'empty-afterglow',
    name: '空镜余韵镜头',
    prompt: '人物离场后保留环境空镜，声音或风景延续情绪',
    scene: '失去之后、结尾回味、情绪收束',
  },
]
