export const CAMERA_FRAMING_TERMS = [
  {
    id: 'close-up',
    name: '特写',
    alias: 'Close-up',
    prompt: '浅景深，面部占画面80%，眼神锐利，背景虚化，情绪聚焦',
    scene: '人物情绪爆发、秘密揭晓前夕',
  },
  {
    id: 'extreme-close-up',
    name: '大特写',
    alias: 'Extreme Close-up',
    prompt: '仅保留眼睛、嘴唇、手指细节，微表情，强压迫感，高反差光影',
    scene: '紧张对峙、关键线索出现',
  },
  {
    id: 'medium-close-up',
    name: '中近景',
    alias: 'Medium Close-up',
    prompt: '胸部以上构图，人物与环境轻度关联，自然视线高度',
    scene: '日常对白、关系升温时刻',
  },
  {
    id: 'medium-shot',
    name: '中景',
    alias: 'Medium Shot',
    prompt: '半身构图，动作与表情并重，叙事平衡，空间关系清楚',
    scene: '双人交流、剧情推进段落',
  },
  {
    id: 'full-shot',
    name: '全景',
    alias: 'Full Shot',
    prompt: '人物完整入镜，肢体语言明确，环境开始参与叙事',
    scene: '出场亮相、行动准备阶段',
  },
  {
    id: 'long-shot',
    name: '远景',
    alias: 'Long Shot',
    prompt: '人物在环境中占比小，空间感明显，氛围主导，留白丰富',
    scene: '孤独行走、命运转折前铺垫',
  },
  {
    id: 'extreme-long-shot',
    name: '超远景',
    alias: 'Extreme Long Shot',
    prompt: '宏大场景，人物极小，建立世界观，电影感天际线',
    scene: '开场建立场、旅程开启、史诗氛围',
  },
  {
    id: 'over-the-shoulder',
    name: '过肩镜头',
    alias: 'Over-the-Shoulder',
    prompt: '前景肩部虚化，对话对象清晰，关系张力，主观代入',
    scene: '谈判、审问、情感对峙',
  },
  {
    id: 'pov-framing',
    name: '主观镜头',
    alias: 'POV',
    prompt: '第一人称视角，视线驱动，沉浸感强，轻微手持感',
    scene: '追逐、发现线索、惊悚遭遇',
  },
  {
    id: 'low-angle-framing',
    name: '低角度镜头',
    alias: 'Low Angle',
    prompt: '机位仰拍，人物更具压迫感与权威感，透视夸张',
    scene: '反派登场、胜利瞬间、英雄塑造',
  },
  {
    id: 'high-angle-framing',
    name: '高角度镜头',
    alias: 'High Angle',
    prompt: '俯拍，角色显得脆弱渺小，信息一览无余',
    scene: '失败时刻、被围困、孤立无援',
  },
  {
    id: 'birds-eye-view',
    name: '鸟瞰镜头',
    alias: "Bird's-eye View",
    prompt: '垂直俯视，图形化构图，调度关系清晰，强设计感',
    scene: '群像调度、案发现场、空间展示',
  },
]
