from __future__ import annotations


EPISODE_RUNTIME_MIN_SECONDS = 75
EPISODE_RUNTIME_MAX_SECONDS = 115
EPISODE_SCENE_MIN = 1
EPISODE_SCENE_MAX = 5
EPISODE_DIALOGUE_LINE_MIN = 20
EPISODE_DIALOGUE_LINE_MAX = 30
EPISODE_SHOT_UNIT_MIN = 15
EPISODE_SHOT_UNIT_MAX = 20
SERIES_RUNTIME_MIN_MINUTES = 100
